/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	appsv1beta1 "github.com/hstreamdb/hstream-operator/api/v1beta1"
)

// ConnectorReconciler reconciles a Connector object
type ConnectorReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

//+kubebuilder:rbac:groups=apps.hstream.io,resources=connectors,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=apps.hstream.io,resources=connectors/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=apps.hstream.io,resources=connectors/finalizers,verbs=update
//+kubebuilder:rbac:groups="",resources=configmaps,verbs=get;create;update;patch;delete

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
// TODO(user): Modify the Reconcile function to compare the state specified by
// the Connector object against the actual cluster state, and then
// perform operations to make the cluster state reflect the state specified by
// the user.
//
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.16.0/pkg/reconcile
func (r *ConnectorReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log = logf.FromContext(ctx)

	var connector appsv1beta1.Connector
	if err := r.Get(ctx, req.NamespacedName, &connector); err != nil {
		log.Error(err, "fail to fetch Connector")

		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	var connectorTemplate appsv1beta1.ConnectorTemplate
	if err := r.Get(ctx, types.NamespacedName{
		Namespace: connector.Namespace,
		Name:      connector.Spec.TemplateName,
	}, &connectorTemplate); err != nil {
		if apierrors.IsNotFound(err) {
			log.Error(err, "ConnectorTemplate not found for Connector",
				"Connector", connector.Name,
				"ConnectorTemplate", connector.Spec.TemplateName,
			)

			return ctrl.Result{}, err
		}

		log.Error(err, "fail to fetch ConnectorTemplate")

		return ctrl.Result{}, err
	}

	templateConfigMapName := appsv1beta1.GenConnectorConfigMapName(connectorTemplate.Name, true)
	templateConfigMapNamespacedName := types.NamespacedName{
		Namespace: connector.Namespace,
		Name:      templateConfigMapName,
	}

	var templateConfigMap corev1.ConfigMap
	if err := r.Get(ctx, templateConfigMapNamespacedName, &templateConfigMap); err != nil {
		log.Error(err, "fail to fetch ConfigMap which stores ConnectorTemplate config")

		return ctrl.Result{}, err
	}

	var templateConfig map[string]interface{}
	err := json.Unmarshal([]byte(templateConfigMap.Data["config"]), &templateConfig)
	if err != nil {
		log.Error(err, "fail to unmarshal ConnectorTemplate config")

		return ctrl.Result{}, err
	}
	stream := connector.Spec.Streams[0]
	templateConfig["stream"] = stream
	if connector.Spec.Patches != nil {
		if val, ok := (*connector.Spec.Patches)[stream]; ok {
			for k, v := range val {
				var vv interface{}

				json.Unmarshal(v, &vv)

				templateConfig[k] = vv
			}
		}
	}
	templateConfigStr, _ := json.Marshal(templateConfig)

	configMapName := appsv1beta1.GenConnectorConfigMapName(connector.Name, false)
	configMapNamespacedName := types.NamespacedName{
		Namespace: connector.Namespace,
		Name:      configMapName,
	}

	var connectorConfigMap corev1.ConfigMap
	if err := r.Get(ctx, configMapNamespacedName, &connectorConfigMap); err != nil {
		if apierrors.IsNotFound(err) {
			err = r.Create(ctx, &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Namespace: connector.Namespace,
					Name:      configMapName,
				},
				Data: map[string]string{
					"config.json": string(templateConfigStr),
				},
			})

			if err != nil {
				log.Error(err, "fail to create ConfigMap for Connector",
					"Connector", connector.Name,
					"ConfigMap", configMapName,
				)

				return ctrl.Result{}, err
			}

			return ctrl.Result{}, nil
		}

		log.Error(err, "fail to fetch ConfigMap which generated by Connector",
			"Connector", connector.Name,
			"ConfigMap", configMapName,
		)

		return ctrl.Result{}, err
	}

	return ctrl.Result{}, nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *ConnectorReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&appsv1beta1.Connector{}).
		Complete(r)
}
