apiVersion: apps.hstream.io/v1alpha1
kind: HStreamDB
metadata:
  labels:
    app.kubernetes.io/name: hstreamdb
    app.kubernetes.io/instance: hstreamdb-sample
    app.kubernetes.io/part-of: hstream-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hstream-operator
  name: hstreamdb-sample
spec:
  config:
    metadata-replicate-across: 3
    nshards: 1
    LogDeviceConfig:
      {
        "rqlite": {
          "rqlite_uri": "ip://localhost:4001"
        }
      }
  image: hstreamdb/hstream
  hserver:
    replicas: 1
    container:
      name: hserver
  hstore:
    replicas: 1
    container:
      name: hstore
  adminServer:
    replicas: 1
    container:
      name: admin-server
