name: Check file

on: [pull_request]

jobs:
  check-manifests-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Check manifests
        run: |
          make manifests
          if ! git diff --quiet; then
            echo "Need run make manifests"
            exit 1
          fi
      - name: Check generate
        run: |
          make generate
          if ! git diff --quiet; then
            echo "Need run make generate"
            exit 1
          fi